### ISSUE TITLE
Feature Request: Helm Repository additional to Git-Repo

### ISSUE THREAD

**Issue by 3deep5me** [mecodia/cert-manager-webhook-hetzner#7]
Hi Folks,

thanks for you work!
I want to try this webhook, during experimenting i saw that there is no Helm-Repo.

My Cert-Manager is deployed via ArgoCD which references a umbrella-chart. (Cert-Manager helm-chart is dependency in the Chart.yaml of the umbrella-chart). It would be really nice if i could just add your chart as a dependency.  At the moment i have to deploy an additional Argo-App or clone the chart into my repo.

```
name: cert-manager-rms-umbrella
version: 0.0.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.11.0
  - name: cert-manager-webhook-hetzner
    repository: https://vadimkim.github.io/cert-manager-webhook-hetzner
    version: 1.1.1
```
